### ISSUE TITLE
HubConnectionBuilder initialization doesn't seem to be called.

### ISSUE THREAD

**Issue by AdmiralSnyder** [BlazorExtensions/SignalR#29]
This is the error i get when trying to build the connection:
(preview 5, server-side blazor.)

Microsoft.JSInterop.JSException: "Could not find 'BlazorExtensions' in 'window'.
Error: Could not find 'BlazorExtensions' in 'window'.
   at Anonymous function (https://localhost:5001/_framework/blazor.server.js:8:20872)
   at Array.prototype.forEach (native code)
   at d (https://localhost:5001/_framework/blazor.server.js:8:20823)
   at Anonymous function (https://localhost:5001/_framework/blazor.server.js:8:21427)
   at Promise (native code)
   at e.jsCallDispatcher.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.server.js:8:21397)
   at Anonymous function (https://localhost:5001/_framework/blazor.server.js:1:16644)
   at Array.prototype.forEach (native code)
   at e.prototype.invokeClientMethod (https://localhost:5001/_framework/blazor.server.js:1:16619)
   at e.prototype.processIncomingData (https://localhost:5001/_framework/blazor.server.js:1:14619)"

**Comment by galvesribeiro** [comment]
Hello @AdmiralSnyder 

Are u able to run the test projects if you just clone the repo and run them?

I'm out on vacation and will take a look at it earlier next month when I get back.

Thanks!

**Comment by galvesribeiro** [comment]
Check the examples. I think you need to register it as "Transient" on DI now.

**Comment by AdmiralSnyder** [comment]
the example is not server-side blazor. 
as to transient: what exactly is it that must be registered?

**Comment by galvesribeiro** [comment]
> the example is not server-side blazor.

For server-side Blazor you don't need this component at all. You can use regular SignalR client from Microsoft.

> as to transient: what exactly is it that must be registered?

Have a look on the README.md. It was updated earlier today and contains an example.

Thanks

**Comment by galvesribeiro** [comment]
I'm closing this issue since it doesn't to seems like a real problem but instead the wrong usage of it.
