### ISSUE TITLE
IL Linker fails to process package

### ISSUE THREAD

**Issue by cswendrowski** [BlazorExtensions/SignalR#41]
Running netcore `3.0.100-preview5-011568`:

```
1>Fatal error in IL Linker
1>
1>Unhandled Exception: Mono.Linker.MarkException: Error processing method: 'System.Void Microsoft.AspNetCore.Blazor.Services.WebAssemblyUriHelper::NotifyLocationChanged(System.String)' in assembly: 'Microsoft.AspNetCore.Blazor.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Microsoft.AspNetCore.Components.UriHelperBase::TriggerOnLocationChanged()
1>   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
1>   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
1>   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
1>   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
1>   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
1>   at Mono.Linker.Steps.MarkStep.ProcessQueue()
1>   --- End of inner exception stack trace ---
1>   at Mono.Linker.Steps.MarkStep.ProcessQueue()
1>   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
1>   at Mono.Linker.Steps.MarkStep.Process()
1>   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
1>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
1>   at Mono.Linker.Pipeline.Process(LinkContext context)
1>   at Mono.Linker.Driver.Run(ILogger customLogger)
1>   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
1>   at Mono.Linker.Driver.Main(String[] args)
```

**Comment by dradovic** [comment]
If you're on preview5 you might want to try the 0.1.9 version of this package.

**Comment by galvesribeiro** [comment]
The preview7 package was published. Please try it out.

**Comment by cswendrowski** [comment]
I verified that package 0.1.9 worked for me - thanks!
