### ISSUE TITLE
Don't work for preview 7

### ISSUE THREAD

**Issue by wiworowa** [BlazorExtensions/SignalR#42]
Unhandled exception. Mono.Linker.MarkException: Error processing method: 'System.Threading.Tasks.Task Blazor.Extensions.HubConnection/<>c__DisplayClass30_0`10::<On>b__0(System.String[])' in assembly: 'Blazor.Extensions.SignalR.dll'
 Mono.Cecil.ResolutionException: Failed to resolve !!0 System.Text.Json.Serialization.JsonSerializer::Parse(System.String,System.Text.Json.Serialization.JsonSerializerOptions)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()

**Comment by galvesribeiro** [comment]
THe preview7 package was published recently. Please try update the package.

**Comment by dmarchant** [comment]
Many thanks for creating this!

I am seeing a similar issue with preview 8 (released yesterday)

When I try to update the code similar to the preview 7 pull request I get a Mono.Linker.MarkException on Failed to resolve Microsoft.AspNetCore.Components.UIEventArgs

Any ideas on how to resolve this?
