### ISSUE TITLE
Upgrading to .NET Standard 2.1 in the Blazor client-side project causes a runtime error

### ISSUE THREAD

**Issue by gandhibobandhi** [BlazorExtensions/SignalR#67]
Upon starting the project, I get the following error. It appears to be looking for a `dist` folder, which is not present when building against .NET Standard 2.1 (but is there for version 2.0):

```
System.IO.DirectoryNotFoundException: /home/adam/Source/Kartel/Kartel.Web/bin/Debug/netstandard2.1/dist/
  at at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
  at at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
  at at Microsoft.AspNetCore.Builder.BlazorHostingApplicationBuilderExtensions.UseClientSideBlazorFiles(IApplicationBuilder app, String clientAssemblyFilePath)
  at at Microsoft.AspNetCore.Builder.BlazorHostingApplicationBuilderExtensions.UseClientSideBlazorFiles[TClientApp](IApplicationBuilder app)
  at Kartel.Api.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in /home/adam/Source/Kartel/Kartel.Api/Startup.cs:74
  at at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
  at at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  at at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
  at at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
  at at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
  at at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
  at at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
  at at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
  at at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
  at at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
  at at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
  at at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
  at at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
  at Kartel.Api.Program.Main(String[] args) in /home/adam/Source/Kartel/Kartel.Api/Program.cs:11
```

**Comment by gandhibobandhi** [comment]
My apologies, i seem to have misdiagnosed this as an issue with this library but it appears to not be related.
